import React from 'react'

export function SectionRenderer({ section, accent }) {
  if (section.type === 'hero') return <section className="page-section hero-section" style={{ background: `linear-gradient(135deg, ${accent}22, #fff)` }}><div className="hero-copy"><span className="eyebrow">Website builder</span><h1>{section.title}</h1><p>{section.subtitle}</p><div className="hero-actions"><button className="primary-btn">{section.cta}</button><button className="secondary-btn">{section.secondary}</button></div></div><div className="hero-card"><div className="mini-window"><div className="window-header"><span /><span /><span /></div><div className="content-lines"><b style={{ background: accent }} /><b /><b /><b /></div></div></div></section>
  if (section.type === 'features') return <section className="page-section"><div className="section-header"><span className="eyebrow">Features</span><h2>{section.title}</h2></div><div className="feature-grid">{section.items?.map((item) => <div className="feature-card" key={`${item.name}-${item.desc}`}><div className="icon-dot" /><h3>{item.name}</h3><p>{item.desc}</p></div>)}</div></section>
  if (section.type === 'pricing') return <section className="page-section"><div className="section-header"><span className="eyebrow">Pricing</span><h2>{section.title}</h2></div><div className="pricing-grid">{section.plans?.map((plan) => <div className="pricing-card" key={`${plan.name}-${plan.price}`}><h3>{plan.name}</h3><div className="price">{plan.price}<span>/mo</span></div><p>{plan.desc}</p><button className="primary-btn small">Choose</button></div>)}</div></section>
  if (section.type === 'cta') return <section className="page-section"><div className="cta-box"><h2>{section.title}</h2><p>{section.subtitle}</p><button className="primary-btn">{section.cta}</button></div></section>
  if (section.type === 'text') return <section className="page-section text-section"><span className="eyebrow">Content block</span><h2>{section.title}</h2><p>{section.body}</p></section>
  return <footer className="page-footer"><strong>{section.title}</strong><nav>{section.links?.map((link) => <a href="#" key={link}>{link}</a>)}</nav></footer>
}
